# Generated by Django 3.1.4 on 2020-12-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название страны')),
                ('slug', models.SlugField(max_length=300)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название актива')),
                ('current_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Текущая цена')),
                ('opening_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена открытия')),
                ('closing_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена закрытия')),
                ('assets_in_circulation', models.DecimalField(decimal_places=10, default=0, max_digits=25, verbose_name='Активов в обращении')),
                ('purchase_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена покупки')),
                ('selling_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена продажи')),
                ('slug', models.SlugField(max_length=300)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название сектора')),
                ('slug', models.SlugField(max_length=300)),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Сктора',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название актива')),
                ('current_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Текущая цена')),
                ('opening_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена открытия')),
                ('closing_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена закрытия')),
                ('dividends', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Дивиденты')),
                ('outstanding_shares', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Акции в обращении')),
                ('the_next_report', models.DateField(verbose_name='Дата следующего отчета')),
                ('purchase_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена покупки')),
                ('selling_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена продажи')),
                ('slug', models.SlugField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.countries', verbose_name='Страна')),
                ('sectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.sectors', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Акцыя',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название актива')),
                ('current_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Текущая цена')),
                ('opening_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена открытия')),
                ('closing_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена закрытия')),
                ('dividends', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Дивиденты')),
                ('assets_in_circulation', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Активов в обращении')),
                ('asset_class', models.CharField(max_length=300, verbose_name='Класс актива')),
                ('purchase_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена покупки')),
                ('selling_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена продажи')),
                ('slug', models.SlugField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.countries', verbose_name='Страна')),
                ('sectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.sectors', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETF',
            },
        ),
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название актива')),
                ('current_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Текущая цена')),
                ('opening_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена открытия')),
                ('closing_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена закрытия')),
                ('coupon', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Купон')),
                ('bonds_in_circulation', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Облигаций в обращении')),
                ('date_maturity', models.DateField(verbose_name='Дата погашения')),
                ('purchase_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена покупки')),
                ('selling_price', models.DecimalField(decimal_places=10, default=0, max_digits=19, verbose_name='Цена продажи')),
                ('slug', models.SlugField(max_length=300)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.countries', verbose_name='Страна')),
                ('sectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.sectors', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Облигацыя',
                'verbose_name_plural': 'Облигации',
            },
        ),
    ]
